---
wireguard_wg0_interface:
  private_key: '{{ wg_client_private_key }}'
  address: '{{ ansible_default_ipv4.address }}'

wireguard_wg0_peers:
  vpn.desunote.ru:
    public_key: '{{ wg_server_private_key }}'
    endpoint: vpn.desunote.ru:24887
    allowed_ips: 0.0.0.0/0

cinnamon_keybindings:
  - key_name: custom0
    name: Terminator
    bindings:
     - 'Scroll_Lock'
    command: '/usr/bin/terminator'

autostart:
 - xpad

wireguard_networks:
 - wg0
