---
- hosts: home
  gather_facts: no
  tasks:
   - name: Setup main mirror
     become: yes
     template:
       src: apt.list.j2
       dest: /etc/apt/sources.list.d/base.list
     tags:
      - apt
   - name: Install packages
     become: yes
     apt:
       state: installed
       name: '{{item}}'
       update_cache: '{{apt_update_cache}}'
       cache_valid_time: '{{apt_cache_valid_time}}'
     with_items: '{{apt_packages}}'
     tags:
      - apt
   - name: Allow passwordless sudo for sudo group
     become: yes
     lineinfile:
       dest: /etc/sudoers
       state: present
       regexp: '^%sudo'
       line: '%sudo ALL=(ALL) NOPASSWD: ALL'
       validate: 'visudo -cf %s'
     when: passwordless_sudo
     tags:
      - sudo
   - name: Add priveleged users to sudo group
     become: yes
     user: name={{item}} groups=sudo append=yes state=present
     with_items: '{{priveleged_users}}'
     tags:
      - sudo
   - name: Configure umask
     become: yes
     lineinfile:
       line: UMASK={{umask}}
       path: /etc/default/login
       state: present
       create: true
     register: umask_changed
     tags:
      - umask
