---
- hosts: home
  tasks:
   - name: Install group-specific packages
     become: yes
     apt: name='{{item}}' state=installed
     with_items:
      - '{{ops_tools}}'
      - '{{drawing_tools}}'
      - '{{programming_tools}}'
