---
- hosts: all
  gather_facts: no
  tasks:
   - name: add stream group
     become: yes
     group: name=steam state=present
   - name: add steam user
     become: yes
     user:
       name: steam
       group: steam
       createhome: no
   - name: Create steam home and dirs
     become: yes
     file:
       path: '{{ item }}'
       state: directory
       owner: steam
       group: steam
     with_items:
       - /home/steam
       - /home/steam/.pulse
   - name: Query for existing architectures
     command: dpkg --print-foreign-architectures
     register: arch
     changed_when: False
   - block:
      - name: Add i386 architecture
        become: yes
        command: dpkg --add-architecture i386
      - name: Update cache
        become: yes
        apt: update_cache=yes
     when: "'i386' not in arch.stdout"
   - name: Install stream dependencies
     become: yes
     apt: state=installed name={{item}}
     with_items:
      - libc6:i386
      - libgl1:i386
      - libdrm2:i386
      - libgl1-mesa-glx:i386
     tags:
      - deps

- hosts: nvidia
  gather_facts: no
  tasks:
  - name: install nvidia stuff
    become: yes
    apt: state=installed name={{item}}
    with_items:
     - libegl-nvidia0:i386
     - libglx-nvidia0:i386
    tags:
     - deps
     - nvidia

- hosts: all
  gather_facts: yes
  tasks:
   - name: Download steam deb file
     get_url:
       url: https://steamcdn-a.akamaihd.net/client/installer/steam.deb
       dest: '/home/{{ ansible_user }}/.cache/steam.deb'
   - name: Unpack steam without running pre/postinst scripts
     become: yes
     command: dpkg -x /home/{{ ansible_user }}/.cache/steam.deb /home/steam
     args:
      creates: /home/steam/usr/lib/steam/bootstraplinux_ubuntu12_32.tar.xz
   - name: Unpack bootstrap
     become: yes
     become_user: steam
     command: tar xJf usr/lib/steam/bootstraplinux_ubuntu12_32.tar.xz
     args:
       chdir: /home/steam
       creates: /home/steam/steam.sh
   - name: Configuring pulseaudio for steam user
     become: yes
     copy:
      content: |
        default-server = 127.0.0.1
      dest:
        /home/steam/.pulse/client.conf
   - name: Configure pulseaudio access
     become: yes
     lineinfile:
       path: /etc/pulse/default.pa
       line: load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1
     notify: reload pulse

  handlers:
   - name: reload pulse
     command: pulseaudio -k
