---
- hosts: all
  gather_facts: no
  tasks:
   - name: add stream group
     become: yes
     group: name=steam state=present
   - name: add steam user
     become: yes
     user:
       name: steam
       group: steam
       createhome: no
   - name: Query for existing architectures
     command: dpkg --print-foreign-architectures
     register: arch
     changed_when: False
   - block:
      - name: Add i386 architecture
        become: yes
        command: dpkg --add-architecture i386
      - name: Update cache
        become: yes
        apt: update_cache=yes
     when: "'i386' not in arch.stdout"
   - name: Install stream dependencies
     become: yes
     apt: state=installed name={{item}}
     with_items:
      - libc6:i386
      - libgl1:i386
      - libdrm2:i386
      - libegl-nvidia0:i386
      - libglx-nvidia0:i386
     tags:
      - deps
