---
- hosts: desktop
  gather_facts: false
  tasks:
   - name: set high watchers numbers for editors
     become: true
     sysctl:
       key: fs.inotify.max_user_watches
       value: '524288'
       state: present
