---
- hosts: vpn
  tasks:
   - name: Set mirror to testing
     become: yes
     copy:
       content: |
         deb http://mirror.servers.com/debian testing main
         deb-src http://mirror.servers.com/debian testing main
       dest: /etc/apt/sources.list.d/base.list
     notify:
      - apt update
   - name: Pin stable over testing
     become: yes
     copy:
      dest: /etc/apt/preferences
      content: |
        Package: *
        Pin: release a=stable
        Pin-Priority: 900
        
        Package: *
        Pin: release a=testing
        Pin-Priority: 800
   - meta: flush_handlers
   - name: dist upgrade
     become: yes
     apt: upgrade=dist
   - name: reboot if nessesary
     import_role:
       name: george.shuklin.reboot-if-needed-for-upgrade
  handlers:
   - name: apt update
     become: yes
     apt: update_cache=yes
