---
- hosts: wifi
  tasks:
   - name: Disable new names for network ifaces # bug around long usb device names
     become: yes
     file: dest=/etc/systemd/network/99-default.link src=/dev/null state=link
     notify: reload driver
   - name: Install firmware
     become: yes
     apt: name=firmware-linux-nonfree state=installed
     notify: reload driver
   - meta: flush_handlers
   - name: Get current connection list
     command: nmcli c
     register: nmcli_output
     changed_when: False
   - name: Scan for network
     become: yes
     command: nmcli d wifi rescan ssid NET-42
     register: scan_res
     retries: 30
     delay: 2
     until: scan_res is success
     when: wifi_name not in nmcli_output.stdout
   - name: Connect to {{wifi_name}}
     command: nmcli d wifi connect {{wifi_name}} password {{wifi_password}} ifname {{wifi_iface}}
     when: wifi_name not in nmcli_output.stdout
  handlers:
   - name: reload driver
     become: yes
     shell: rmmod {{wifi_driver}}; modprobe {{wifi_driver}}
     when: wifi_driver|default(False)
