---
- hosts: home,vpn
  become: yes
  pre_tasks:
   - name: install kernel headers
     become: yes
     apt: name=linux-headers-amd64 state=installed
  roles:
   - wireguard
  vars:
    server_address: '{{ hostvars[groups.vpn[0]].ansible_default_ipv4.address }}'
