---
- name: Configure {{ item }}
  template:
    src: wgX.conf.j2
    dest: /etc/wireguard/{{ item }}.conf
  register: configuration

- name: Enable wg-quick@{{ item }} service
  service:
    name: wg-quick@{{ item }}
    state: started
    enabled: yes
  tags: install
  when: wireguard_manage_services

- name: Restart wg-quick@{{ item }}
  service:
    name: wg-quick@{{ item }}
    state: restarted
  when: configuration is changed and wireguard_manage_services
