---
- name: Enable wireguard COPR repository
  get_url:
    dest: /etc/yum.repos.d/_copr_jdoss-wireguard.repo
    url: "https://copr.fedorainfracloud.org/coprs/jdoss/wireguard/repo/{{ (ansible_distribution == 'Fedora') | ternary('fedora', 'epel') }}-{{ ansible_distribution_major_version }}/jdoss-wireguard-{{ (ansible_distribution == 'Fedora') | ternary('fedora', 'epel') }}-{{ ansible_distribution_major_version }}.repo"

- name: Enable EPEL
  package:
    name: epel-release
    state: present
  when: ansible_distribution != "Fedora"

- name: Install wireguard
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - wireguard-dkms
    - wireguard-tools
